external_host_name = "moneyclaims.perftest.platform.hmcts.net"
idam_api_url = "https://idam-api.perftest.platform.hmcts.net"
authentication_web_url = "https://idam-web-public.perftest.platform.hmcts.net"
capacity = "2"
feature_mock_pay =  "true"
